### ISSUE TITLE
join.skype.com

### ISSUE THREAD

**Issue by bonanza123** [phts/firefox-web-skype#1]
Please apply the same trick to `join.skype.com` links

**Comment by phts** [comment]
Ok, will add soon.

**Comment by phts** [comment]
@bonanza123  join.skype.com redirects me to https://www.skype.com/en/

What is this join.skype.com for and how to use it?

**Comment by bonanza123** [comment]
`join.skype.com/.../ID` links are created conference links (for guys to join based on URL). It is similar to `web.skype.com` but for conferences I guess.

**Comment by phts** [comment]
Added in v0.4.0

However I did not have a chance to test it. Feel free to reopen the issue if it does not work.
