### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by bonanza123** [phts/firefox-web-skype#2]
Would it be possible to release a version that is compatible with firefox for android?

**Comment by phts** [comment]
Actually never used web version in firefox android. Will try to add support for it soon.

**Comment by phts** [comment]
@bonanza123 Just tested: added this extension to ff on Android, opened web.skype.com and **it works**. Before installation this extension skype didn't work.
FF 66.0.2
Android 7
Sony F3111

Any problems with this on your device?

**Comment by bonanza123** [comment]
I could not find the addon on FF for android, that's why I thought that Mozilla labeled it as incompatible. Was I just blind?

**Comment by phts** [comment]
Try to open direct link https://addons.mozilla.org/firefox/addon/firefox-web-skype/

Also I have explicitly set in addon's settings to support FF for android 59+. Should be listed now (maybe after some delay).

**Comment by phts** [comment]
@bonanza123 Feel free to reopen this issue if it still doesn't work.
