### ISSUE TITLE
STARTUP_LOAD_ERROR

### ISSUE THREAD

**Issue by sliusar** [phts/firefox-web-skype#3]
Hi there,

It seems Microsoft/Skype hardened the Chrome-dependency even more, neither with this plugin, nor with generic (Firefox-wide) agent switcher, the web.skype.com doesn't work any more, it just outputs "Oops, there was a problem with Skype. Try switching out and back in ... STARTUP_LOAD_ERROR" message. I'm using Firefox 65.0.1 on Debian 9.8 (x86_64).

**Comment by marcrobledo** [comment]
It's still working for me with both user agent switcher and this plugin.

**Comment by phts** [comment]
@sliusar I cannot reproduce it either on Firefox 65.0.1 (however on win7). 

Could you please provide more info if possible, maybe some suspicious errors/warnings in console.

Or maybe Microsoft performs A/B testing with functionality against switching `userAgent`. And you are inside this testing group. @marcrobledo and me are outside. :confused:

**Comment by sliusar** [comment]
I've tried with most recent Firefox 66, also in private browsing, so that cookies don't propagate, same problem.

Edit: I've also tried on a Macbook (macOS 10.14.4), Firefox 66.0.3, same error. The only thing I might think of, which somehow makes my account different from usual ones, is that I have a paid account, i.e. I occasionally use Skype to call landline phones.

**Comment by sliusar** [comment]
@phts regarding the errors, most of the output looks normal, some GET/POST requests, except for numerous errors:

```
downloadable font: gasp: Changed the version number to 1 (font-family: "Segoe UI Web Regular" style:normal weight:400 stretch:100 src index:2) source: https://secure.skypeassets.com/apollo/2.0.127/fonts/latin/segoe-ui-regular-latin.ttf
downloadable font: gasp: Changed the version number to 1 (font-family: "Segoe UI Web Light" style:normal weight:200 stretch:100 src index:2) source: https://secure.skypeassets.com/apollo/2.0.127/fonts/latin/segoe-ui-light-latin.ttf
downloadable font: maxp: Bad maxZones: 0 (font-family: "SkypeAssets-Light" style:normal weight:400 stretch:100 src index:1) source: https://secure.skypeassets.com/wcss/8-44-0-40/fonts/SkypeAssets-Light.woff
downloadable font: OS/2: Bad yStrikeoutSize: -237, setting it to zero (font-family: "SkypeAssets-Light" style:normal weight:400 stretch:100 src index:1) source: https://secure.skypeassets.com/wcss/8-44-0-40/fonts/SkypeAssets-Light.woff
```
And 404 for following url GET request:
`https://client-s.gateway.messenger.live.com/v1/users/ME/properties`

**Comment by phts** [comment]
@sliusar Actually I have no idea what's going on. Most likely the problem is not on plugin's side because generic agent switcher also does not work for you. Maybe more hacks are needed for paid account but I cannot check that.

I will reopen this issue if Skype will not work for me as well.

**Comment by mitomenai** [comment]
media.peerconnection.enabled has to be enabled in about:config, otherwise you'll encounter this issue.
