### ISSUE TITLE
No audio using Skype Out to Phones

### ISSUE THREAD

**Issue by Woolwit** [phts/firefox-web-skype#4]
Text and calls to computers work great. Unfortunately I'm not able to connect to phones via Skype Out. The recipient's phone will ring, but there is neither incoming nor out going sound.

**Comment by phts** [comment]
@Woolwit could you please add steps to reproduce it and what URLs are used? I have never tried Skype Out.

But most likely this is issue not related to this plugin. Skype uses webrtc protocol with non-standard extensions which work only in Chrome. That's why Microsoft turned off support for FF.

**Comment by Woolwit** [comment]
Yes, probably not related to the plugin. I'm not sure now how it works other than... try calling an actual phone using the touch pad in Skype... you'll probably be directed to a page asking you to buy some Skype Out time. Probably beyond the scope of this plugin. Just weird that it works great Skype to Skype but not Skype Out.  Thanks!
