### ISSUE TITLE
Cannot launch Skype

### ISSUE THREAD

**Issue by clement-escolano** [phts/firefox-web-skype#5]
Hello!

Sorry to post an issue, it seems to work for a lot of people but it is not working on my end.
I create a meeting with the "meet now" button, (a link is created, to be shared with the people you want to talk to). Then I press the button "Start call". I select only the audio option as it is written that video does not work in the README, then "Start call" again.
The call seems to start and then immediately fails. It sometimes tells me my connection is low (it is not, and Skype works on Chrome on my computer).

In the console, I see these errors when I press "Start call":

```
TypeError: RTCPeerConnection.getStats: Argument 1 does not implement interface MediaStreamTrack.
Using more than two STUN/TURN servers slows down discovery
onaddstream is deprecated! Use peerConnection.ontrack instead.
```

There are calls to `/consumptionhorizons` and `/relay` endpoints but none of them seems to fail.

Do you know if I am doing something wrong?

Thank you

**Comment by phts** [comment]
Hi @clement-escolano!

This plugin allows you to open _web.skype.com_ web page by replacing `userAgent` only but it cannot fix any issues related to WebRTC protocol.

Historically, the reason why Firefox was blocked to _Skype for Web_ was the difference in implementations of WebRTC API. Firefox implemented it according to official API. However Chrome (And Edge) implemented it with non-standard extensions, so in some cases Firefox may just not understand it.

While some basic stuff may still work (e.g messaging which does not require WebRTC), but more complex stuff related to WebRTC (calls) may not work. Like in your case.

Microsoft did not provide Skype with cut functionality (e.g. only with messaging) to Firefox users, they just turned off whole application in Firefox. 

So I cannot help in your case. Unfortunately.

**Comment by clement-escolano** [comment]
Thank you for your answer.
OK I see better the problem now. I think this can be added in the README that all call features are not supported except messaging. I thought it was a problem on my end because there were a lot of comments on the mozilla addon page saying everything was working perfectly.

Anyway, I hope Skype will some day change to be compatible with Firefox.

Have a good week-end

**Comment by phts** [comment]
> I think this can be added in the README that all call features are not supported except messaging.

Already :)

**Comment by clement-escolano** [comment]
> > I think this can be added in the README that all call features are not supported except messaging.
> 
> Already :)

Maybe this is intentionnally vague but I think it will be less deceptive to state more clearly the users to say that video and audio call do not work. Right now, `video calls and other features may still not work on Firefox` may let think that audio calls work.
